name: Build CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Jobul de testare (trebuie definit primul sau referențiat)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      # TODO 01 - Am adăugat comanda de testare
      - name: Run tests
        run: go test ./...

  # Jobul de compilare
  compile:
    runs-on: ubuntu-latest
    # TODO 02 - Specificăm că acest job depinde de succesul jobului 'test'
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Compile binary
        run: go build -o myapp
